### PR TITLE
add initial CMakeLists.txt

### PR DESCRIPTION
**Pull request by gregorburger**
- tested in MSYS2

### CODE REVIEW

**Comment by perkele1989** [comment]
I like how clean your version is, however this breaks with Ubuntu 15.10 because of the cmake version requirement. Changing 3.3 to 3.2 fixes this.

Also, your cmakelists is broken, you link to particle target but the executable is particles. No idea how you couldve successfully tested this in msys2

**Comment by perkele1989** [comment]
Also, dont know if you missed my pull req here https://github.com/MauriceGit/Partikel_accelleration_on_GPU/pull/1

**Comment by gregorburger** [comment]
no clue how this worked! but it did...

**Comment by perkele1989** [comment]
Still problems with your pull req. You link to GLUT although you dont need to. And you add header files to the "add_executable" command.

**Comment by perkele1989** [comment]
Btw, did my pull request work on your system? Or why did you create another one? :)

**Comment by MauriceGit** [comment]
I think he didn't see the first :)

https://www.reddit.com/r/programming/comments/40ri26/particle_simulation_with_opengl_compute_shader_8m/

**Comment by gregorburger** [comment]
@haikarainen 
In order for headers to show up in QtCreator (maybe also other IDEs) they need to be added to add_executable. At least that was the case when I last checked. 
@MauriceGit yeah was not looking at your pulls

**Comment by MauriceGit** [comment]
Thank you both for your effort.
But I decided to go for a simple make instead of cmake because I worked a lot with make and never really with cmake. So I feel  more comfortable with it.

**Comment by MauriceGit** [comment]
I also can't get your cmake to run properly...

/usr/bin/ld: //usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [particles] Fehler 1
make[1]: **\* [CMakeFiles/particles.dir/all] Fehler 2
make: **\* [all] Fehler 2

**Comment by MauriceGit** [comment]
All right, changed to cmake with GLEW and GLFW now included locally :)

**Pull request closed without merging**
