### PR TITLE
Makefile and .gitignore

### PR DESCRIPTION
**Pull request by arsv**
Common make is more than enough to build this project.

### CODE REVIEW

**Comment by perkele1989** [comment]
... And that's how you kill cross-platform support

**Comment by MauriceGit** [comment]
I couldn't get the cmakes to run...

If you can get around this error, I might go for cmake...

/usr/bin/ld: //usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [particles] Fehler 1
make[1]: **\* [CMakeFiles/particles.dir/all] Fehler 2
make: **\* [all] Fehler 2

**Comment by perkele1989** [comment]
What distribution are you running and how did you install GLFW? Seems to be a problem with your GLFW build

**Comment by MauriceGit** [comment]
Mint 17.2 and I it's been quite a while since I installed GLFW. But I think I compiled/installed it from source code.

**Comment by MauriceGit** [comment]
All right, changed to cmake with GLEW and GLFW now included locally :)

**Pull request merged**
