### PR TITLE
Added CMake support

### PR DESCRIPTION
**Pull request by perkele1989**
Added support for CMake by creating a CMakeLists.txt, I also created a .gitignore containing a build-directory (to exclude CMake builds), and the particles-binary created by compile.sh.

This is my first pull request on github so please be gentle.

### CODE REVIEW

**Comment by MauriceGit** [comment]
Hey haikarainen,

thanks a lot for your effort! As mentioned in the other pull request, I decided to go for a simple makefile because I don't know much about cmake...
But I appreciate it and good luck on your next pull request :)

**Comment by perkele1989** [comment]
Cool, CMake has the benefit of cleanly separating the build process from the platform. My CMakeLists.txt would compile under windows/mac as well. The makefile you merged is as platformdependent as your compile.sh script

**Comment by MauriceGit** [comment]
When I try your cmake, it doesn't work out of the box.
cmake . && make

**Comment by MauriceGit** [comment]
All right, changed to cmake with GLEW and GLFW now included locally :)

**Pull request closed without merging**
