### PR TITLE
Made easier to compile on Win32 and added CMakeList.txt

### PR DESCRIPTION
**Pull request by MenaceInc**
For Ubuntu 14.04 and Linux Mint:
All that the user needs to do is ensure they have the following installed: cmake
g++
libglfw-dev
libxrandr-dev
libxinerama-dev

then run: "cmake CMakeLists.txt", "make", "cd bin", "./particleSim".

All necessary shader files and executable are put into the bin/ folder at the root of the project.

All of this also allows the code to be compiled with CLion.

For Windows 7/8/10:
Should be able to just open the CMakeLists.txt in CLion and hit compile.

### CODE REVIEW

**Comment by MenaceInc** [comment]
I know that you've said that you are unfamiliar with CMake but I would recommend having a look into it. You can easily get a grasp of the basic build flow in an evening and it allows you to create project files for Visual Studio or Eclipse, regular make files (as seen in this PR) and some IDEs such as CLion work with CMake files natively.

Also, I know that you may not like the GLFW and GLEW libraries being included but this is the simpliest way to ensure that all necessary files are included and available _no matter what platform it is being compiled on_ (including Windows). The libraries can easily be updated and the references changed in the CMakeLists.txt file in the case of any updates.

**Comment by MenaceInc** [comment]
Sorry, I meant to say I tested this (using the CMake file) on Ubuntu 14.04, not 14.10.
It was also tested on Linux Mint using the same file.

**Comment by MauriceGit** [comment]
Hey MenaceInc,
Actually, I like it a lot, that GLEW and GLFW are now included locally!!! That avoids so much potential trouble with people (or me) not having those installed and messing around with it.
And it's two things no one has to think about any more. 
So, I very much appreciate your approach and Pull request!
Just tried it and it runs very well out of the box.
So I merged it into the master-branch :)

Thanks all of you for you ideas and help!

**Comment by MenaceInc** [comment]
Hi Maurice,

No problem at all.It's an interesting project and I wanted to test it out on my Windows machine anyway.

Just a note as well and I think someone mentioned it on reddit but this won't be able to run on Mac OS as OpenGL support is limited to 4.1 while the compute shaders require 4.3.

You could amend the readme to reflect that it compiles/runs on Windows and Linux but not Mac OS (and make sure to say that Apple have limited Mac OS's OpenGL support, don't want any issues raised over something you can't help).

Well done on the project.

**Pull request merged**
